### PR TITLE
fix(steps): fix step item extra

### LINKED ISSUE #36: steps(bug):
**Describe Framework**
- [x] tdesign-vue
- [ ] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

官网

**streps 组件 extra demo**

未出现 extra 内容
image

### PR DESCRIPTION
**Pull request by LuckyWinty**
fix #36

- Component Name: steps.
- [issue#36](https://github.com/Tencent/tdesign-vue/issues/36)，[LuckyWinty](https://github.com/LuckyWinty)

- steps: 修复 step item extra 没有渲染出来的问题

--------

**brefore**
image

.....

**after**
image

......

### CODE REVIEW

File: src/steps/steps.tsx [hunk 1]
```diff
@@ -56,25 +56,48 @@ export default mixins(getConfigReceiverMixins('steps')).extend({
...
+        return (
+          <t-step-item
+            props={{
+              ...item,
+              status: this.handleStatus(item, index),
+            }}
+            key={item.value || index}
+          ></t-step-item>
+        );
+      }
```
Comment (chaishi) [inline src/steps/steps.tsx:81]: 代码调整有点疑惑，思考确认中...

File: src/steps/steps.tsx [hunk 2]
```diff
@@ -56,25 +56,48 @@ export default mixins(getConfigReceiverMixins('steps')).extend({
...
+      return (
         <t-step-item
           props={{
             ...item,
             status: this.handleStatus(item, index),
           }}
           key={item.value || index}
         ></t-step-item>
-    ));
+      );
```
Comment (chaishi) [inline src/steps/steps.tsx:90]: line#73 ~ line#79 和 line#83 ~ line#89，代码重复，需要优化

Comment (LuckyWinty) [reply src/steps/steps.tsx:75]: 已改
